name:  nigori
description:  Secrets in the cloud

dependencies:
  unittest:
  json_object:
  bignum:
    git: git://github.com/ucam-cl-dtg/dart-bignum.git
  protobuf:
    git: git://github.com/ucam-cl-dtg/dart-protobuf.git