name: nigori
description: Secrets in the cloud
dependencies:
  unittest: any
  json_object:
    git: git://github.com/ucam-cl-dtg/dartwatch-JsonObject.git
  protobuf:
    git: git://github.com/ucam-cl-dtg/dart-protobuf.git
  bignum:
    git: git://github.com/ucam-cl-dtg/dart-bignum.git
