name: nigori
description: Secrets in the cloud
dependencies:
  unittest: any
  json_object: 1.0.7
  protobuf:
    git: git://github.com/ucam-cl-dtg/dart-protobuf.git
  bignum:
    git: git://github.com/ucam-cl-dtg/dart-bignum.git
